// eslint-disable-next-line no-unused-vars
const categoryList = [
  { code: 'all', name: 'All' },
  { code: 'agents', name: 'Agents' },
  { code: 'art', name: 'Art' },
  { code: 'audio', name: 'Audio' },
  { code: 'book', name: 'Book' },
  { code: 'blogging', name: 'Blogging' },
  { code: 'branding', name: 'Branding' },
  { code: 'business', name: 'Business' },
  { code: 'coding', name: 'Coding' },
  { code: 'copywriting', name: 'Copywriting' },
  { code: 'creative', name: 'Creative' },
  { code: 'data', name: 'Data' },
  { code: 'design', name: 'Design' },
  { code: 'education', name: 'Education' },
  { code: 'extraction', name: 'Extraction' },
  { code: 'fantasy', name: 'Fantasy' },
  { code: 'food', name: 'Food' },
  { code: 'email', name: 'Email' },
  { code: 'games', name: 'Games' },
  { code: 'general', name: 'General' },
  { code: 'health_and_wellness', name: 'Health & Wellness' },
  { code: 'ideas', name: 'Ideas' },
  { code: 'image_generation', name: 'Image Generation' },
  { code: 'jailbreak', name: 'Jailbreak' },
  { code: 'learning', name: 'Learning' },
  { code: 'legal', name: 'Legal' },
  { code: 'literature', name: 'Literature' },
  { code: 'marketing', name: 'Marketing' },
  { code: 'movies', name: 'Movies' },
  { code: 'news', name: 'News' },
  { code: 'personal', name: 'Personal' },
  { code: 'photography', name: 'Photography' },
  { code: 'productivity', name: 'Productivity' },
  { code: 'real_estate', name: 'Real Estate' },
  { code: 'relationship', name: 'Relationship' },
  { code: 'research', name: 'Research' },
  { code: 'science', name: 'Science' },
  { code: 'saas', name: 'SaaS' },
  { code: 'seo', name: 'SEO' },
  { code: 'social_media', name: 'Social Media' },
  { code: 'summarization', name: 'Summarization' },
  { code: 'tagging', name: 'Tagging' },
  { code: 'tones', name: 'Tones' },
  { code: 'translation', name: 'Translation' },
  { code: 'videos', name: 'Videos' },
];
