// eslint-disable-next-line no-unused-vars
const categoryList = [
  { code: 'all', name: 'All' },
  { code: 'blogging', name: 'Blogging' },
  { code: 'business', name: 'Business' },
  { code: 'coding', name: 'Coding' },
  { code: 'copywriting', name: 'Copywriting' },
  { code: 'creative', name: 'Creative' },
  { code: 'design', name: 'Design' },
  { code: 'education', name: 'Education' },
  { code: 'email', name: 'Email' },
  { code: 'games', name: 'Games' },
  { code: 'general', name: 'General' },
  { code: 'ideas', name: 'Ideas' },
  { code: 'image_generation', name: 'Image Generation' },
  { code: 'jailbreak', name: 'Jailbreak' },
  { code: 'learning', name: 'Learning' },
  { code: 'legal', name: 'Legal' },
  { code: 'marketing', name: 'Marketing' },
  { code: 'productivity', name: 'Productivity' },
  { code: 'research', name: 'Research' },
  { code: 'saas', name: 'SaaS' },
  { code: 'seo', name: 'SEO' },
  { code: 'tones', name: 'Tones' },
  { code: 'translation', name: 'Translation' },
  { code: 'videos', name: 'Videos' },
];
